"""添加接口表

Revision ID: 12e66cace0b5
Revises: 56a38dbec9cd
Create Date: 2026-05-22 17:20:43.146004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12e66cace0b5'
down_revision = '56a38dbec9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('resource', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=True))
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'resources', ['pid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('pid')

    op.drop_table('interfaces')
    # ### end Alembic commands ###
